config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pins do
    delete 'delete_image/:image_id', on: :member, to: 'pins#delete_image', as: 'delete_image'
  end

  resources :contacts
  get 'pages/index'
  get 'pages/about'
  get 'pages/contact'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pins#index'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new
    can :read, Pin

    if user.admin_role?
      can :manage, Pin
    elsif user.author_role?
      can [:create, :read], Pin
      can [:update, :destroy, :delete_image], Pin, user_id: user.id
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: { message: 'Es obligatorio'}
  validates :mail, presence: { message: 'Es obligatorio'}
  validates :message, presence: { message: 'Es obligatorio'}
end

app/models/pin.rb
class Pin < ApplicationRecord
  has_many_attached :images
  validates :title, presence: { message: 'Es obligatorio'}
  validates :description, presence: { message: 'Es obligatorio'}
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  has_many :pins, dependent: :destroy
  has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to main_app.root_url, notice: exception.message
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :image])
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to action: "new", notice: 'Contacto enviado.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:name, :mail, :message)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  load_and_authorize_resource
  before_action :set_pin, only: [:show, :edit, :update, :destroy]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = Pin.new
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = Pin.new(pin_params)
    @pin.user = current_user
    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin creado exitosamente.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin actualizado.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin eliminado.' }
      format.json { head :no_content }
    end
  end

  def delete_image
    begin
      @image = ActiveStorage::Attachment.find(params[:image_id])
      @image.purge
      redirect_to pin_path(@pin), notice: 'Imagen eliminada con éxito'
    rescue ActiveRecord::RecordNotFound
      redirect_to pin_path(@pin), alert: 'Error al eliminar la imagen'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pin_params
      params.require(:pin).permit(:title, :description, images: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation" class="alert alert-secondary" role="alert">
      <h3><%= pluralize(contact.errors.count, "error") %> verifica los siguientes datos:</h3>

      <ul>
        <% contact.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :name, 'Nombre' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :mail %>
    <%= form.text_field :mail, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :message, 'Mensaje' %>
    <%= form.text_area :message, class: 'form-control' %>
  </div>

  <div class="actions form-group">
    <%= form.submit 'Enviar contacto', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Mail</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.mail %></td>
        <td><%= contact.message %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<header class="fondo-contacto">
  <h1 class="display-4 color-1 text-center sombra">Contacto</h1>
  <h5 class="display-4 color-2 text-center sombra">vulputate eget pellentesque at, ultricies in leo. Donec sapien mi</h5>
</header>
<div class="container mt-2">
  <div class="row">
    <div class="col-lg-6">
      <h2 class="text-center">¿Como te ayudamos?</h2>
      <ul>
        <li class="mt-3">
          <span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec convallis ante vitae lacinia luctus. Donec in dui at erat tincidunt maximus. Nulla quis ante volutpat, pulvinar arcu quis, varius dolor. Morbi ut varius lacus, in tincidunt ligula. Fusce vel ultricies nisi, sed fermentum felis</span>
        </li>
        <li class="mt-3">
          <span>Phasellus at scelerisque mauris, ut tincidunt massa. Sed vestibulum, nisl a dapibus tempus, felis ex iaculis enim, a dapibus lectus justo quis velit</span>
        </li>
        <li class="mt-3">
          <span>Nulla laoreet consequat libero iaculis mollis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aliquam massa tellus</span>
        </li>
      </ul>
    </div>
    <div class="col-lg-6">
      <% if flash[:notice] %>
        <p id="notice" class="alert alert-dark"><%= notice %></p>
      <% end %>
      <div class="card mb-3">
        <h5 class="card-header">Contactanos</h5>
        <div class="card-body">
          <%= render 'form', contact: @contact %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Mail:</strong>
  <%= @contact.mail %>
</p>

<p>
  <strong>Message:</strong>
  <%= @contact.message %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.4.1/cosmo/bootstrap.min.css" rel="stylesheet" integrity="sha384-qdQEsAI45WFCO5QwXBelBe1rR9Nwiss4rGEqiszC+9olH1ScrLrMQr1KmDR964uZ" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <title>Hello, world!</title>
  </head>
  <body>
      <%= render 'shared/navbar' %>
      <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="fondo">
</div>
<div class="container-fluid container-index">
  <div class="row">
    <div class="col-lg-6">
      <%= image_tag('back-header.jpg') %>
    </div>
    <div class="col-lg-6">
      <div class="card">
        <div class="card-body">
          <h1>¿Quienes somos?</h1>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec convallis ante vitae lacinia luctus. Donec in dui at erat tincidunt maximus. Nulla quis ante volutpat, pulvinar arcu quis, varius dolor. Morbi ut varius lacus, in tincidunt ligula. Fusce vel ultricies nisi, sed fermentum felis. Fusce posuere nulla et velit placerat, eu tincidunt nulla rutrum. Etiam nec lorem finibus, mollis sapien eget, hendrerit diam. Donec dui enim, volutpat vitae blandit eget, feugiat a orci. Fusce aliquet vel tellus eget feugiat. Morbi lectus ligula, sodales vestibulum nibh interdum, pulvinar tincidunt elit.

            Phasellus at scelerisque mauris, ut tincidunt massa. Sed vestibulum, nisl a dapibus tempus, felis ex iaculis enim, a dapibus lectus justo quis velit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam convallis vulputate risus, efficitur porta ex. Aliquam at finibus lectus. Pellentesque in nisl lectus. Duis ac felis vulputate, dapibus urna at, interdum orci. Aenean ornare elementum porta. Morbi a nibh lacinia, rutrum lacus id, egestas felis. Suspendisse non maximus nisl. Quisque urna nibh, eleifend vitae posuere vitae, mattis eget erat.

            Nulla laoreet consequat libero iaculis mollis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aliquam massa tellus, vulputate eget pellentesque at, ultricies in leo. Donec sapien mi, tempor at semper id, viverra non enim. Pellentesque semper ligula id posuere pretium. Pellentesque luctus eu odio sed lobortis. Maecenas in mauris volutpat magna placerat semper rhoncus sit amet purus. Sed elit nibh, laoreet sed tristique at, accumsan vitae quam. Sed ut ligula quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent fermentum enim vitae laoreet pellentesque. Donec at iaculis sapien, quis vehicula velit. Nulla ut venenatis tellus.
          </p>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/pages/index.html.erb
<div class="fondo">
</div>
<header class="container-index">
  <h1 class="display-4 color-1 text-center">Dibujos animados</h1>
</header>
<div class="container container-index">
</div>

app/views/pins/_form.html.erb
  <%= form_with(model: pin, local: true) do |form| %>
    <% if pin.errors.any? %>
      <div id="error_explanation" class="alert alert-secondary" role="alert">
        <h2>verifique los siguientes datos para continuar:</h2>
        <ul>
          <% pin.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form-group">
        <%= form.label :title, 'Titulo' %>
        <%= form.text_field :title, class: 'form-control', placeholder:'Titulo' %>
    </div>
    <div class="form-group">
      <%= form.label :description, 'Descripción' %>
      <%= form.text_area :description, class: 'form-control', placeholder:'Descripción' %>
    </div>
    <div class="field custom-file form-group">
      <%= form.label :images, class: "custom-file-label" %>
      <%= form.file_field :images, multiple: true, class: "custom-file-input" %>
    </div>
    <% if @pin.images.attached? %>
      <div class="row mt-3">
        <% @pin.images.each do |image| %>
          <div class="col-6 col-md-2 text-center">
            <%= image_tag image, class: "w-100" %>
            <br>
            <%= link_to 'Remover', delete_image_pin_path(@pin, image), method: :delete, data: { confirm: '¿Está seguro?' }, class: 'btn btn-danger' %>
          </div>
        <% end %>
      </div>
    <% end %>
    <div class="form-group mt-3">
      <%= form.submit 'Agregar', class: 'btn btn-primary' %>
    </div>
  <% end %>

app/views/pins/edit.html.erb
<div class="fondo">
</div>
<div class="container mt-5 pt-5">
  <div class="card mb-3">
    <h5 class="card-header">Editar Pin</h5>
    <div class="card-body">
      <%= render 'form', pin: @pin %>

      <%= link_to 'Ver', @pin, class: 'btn btn-secondary' %> |
      <%= link_to 'Volver', pins_path, class: 'btn btn-secondary' %>
    </div>
  </div>
</div>

app/views/pins/index.html.erb
<div class="fondo">
</div>
<header class="container-index">
  <h1 class="display-4 color-1 text-center">Dibujos animados</h1>
  <h5 class="display-4 color-2 text-center">vulputate eget pellentesque at, ultricies in leo. Donec sapien mi</h5>
</header>
<div class="container container-index">
  <%= render 'shared/cards' %>
  <div class="row">
    <div class="col my-4 text-center">
      <%= link_to  "Agregar Pin", { controller: 'pins', action: 'new'}, class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/pins/new.html.erb
<div class="container mt-6">
  <div class="card mb-3">
    <h5 class="card-header">Nevo Pin</h5>
    <div class="card-body">
      <%= render 'form', pin: @pin %>

      <%= link_to 'Volver', pins_path, class: 'btn btn-secondary' %>
    </div>
  </div>
</div>

app/views/pins/show.html.erb
<div class="fondo">
</div>
<div class="container mt-5 pt-5">
  <div class="row">
    <div class="col">
      <% if flash[:notice] %>
        <p id="notice" class="alert alert-dark"><%= notice %></p>
      <% end %>
      <p>
        <strong>Titulo:</strong>
        <%= @pin.title %>
      </p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-header">
              <strong>Descripción:</strong>
            </div>
            <div class="card-body">
              <%= @pin.description %>
            </div>
          </div>
        </div>
        <div class="col-12 mt-4">
          <div class="row">
            <% @pin.images.each do |image| %>
              <div class="col-4">
                <%= image_tag image, class: 'w-100' %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <%= image_tag @pin.images[0], class: 'img-fluid' %>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <% if can? :update, @pin %>
        <%= link_to 'Editar', edit_pin_path(@pin), class: 'btn btn-secondary' %> |
      <% end %>
      <%= link_to 'Volver', pins_path, class: 'btn btn-secondary' %>
    </div>
  </div>
</div>

app/views/shared/_cards.html.erb
<div class="row">
    <% @pins.each do |pin| %>
      <div class="col-lg-4 col-md-6 mb-3">
        <div class="card mx-auto" style="width: 18rem;">
            <% if pin.images.attached? %>
              <%= image_tag pin.images[0], class: "img-fluid" %>
            <% end %>
            <div class="card-body">
                <h5 class="card-title text-center"><%= pin.title %></h5>
                <p class="card-text"><%= pin.description %></p>
                <div class="text-center">
                  <%= link_to 'Ver', pin, class: 'btn btn-primary' %>
                  <% if can? :update, pin %>
                    <%= link_to 'Editar', edit_pin_path(pin), class: 'btn btn-success' %>
                  <% end %>
                  <% if can? :destroy, pin %>
                    <%= link_to 'Eliminar', pin, method: :delete, data: { confirm: '¿Estas seguro?' }, class: 'btn btn-danger' %>
                  <% end %>
                </div>
            </div>
        </div>
    </div>
    <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="#">Caricaturas</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
      <%= link_to  "Home", { controller: '/pins', action: 'index'}, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to  "Contacto", { controller: '/contacts', action: 'new'}, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to  "Acerca de", { controller: '/pages', action: 'about'}, class: 'nav-link' %>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
        <% if current_user.image.attached? %>
          <%= image_tag current_user.image.variant(resize: '35x35^', extent: '35x35^', gravity: 'center'), class: 'rounded-circle' %>
        <% end %>
        </li>
        <li class="nav-item">
            <%= link_to 'Hola ' + current_user.name, edit_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Cerrar sesion', destroy_user_session_path, method: :delete, class: "nav-link" %>
        <li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Iniciar sesion', new_user_session_path, class: "nav-link" %>
        <li>
        <li class="nav-item">
            <%= link_to 'Registrarse', new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>